[package]
name = "cloc-lang"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Language definition tables for cloc"

[dependencies]
anyhow.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
